loginExample/Models/Inspection.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace loginExample.Models
{
    public class Inspection
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int InspectionID { get; set; }
        public int PropertyID { get; set; }
        public string Details { get; set; }
        public bool InspectionStatus { get; set; }
        public DateTime InspectionDate { get; set; }
        public bool Active { get; set; }
    }
}

loginExample/Models/InspectionDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace loginExample.Models
{
    public class InspectionDetails
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int InspectionID { get; set; }
        public int PropertyID { get; set; }
        public string Details { get; set; }
        public bool InspectionStatus { get; set; }
        public DateTime InspectionDate { get; set; }
        public bool Active { get; set; }
        public string PropertyName { get; set; }

        public List<InspectionItemDetails> inspectionItems { get; set; }

    }
}

loginExample/Models/InspectionItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace loginExample.Models
{
    public class InspectionItem
    {
        [Key]
        public int ItemID { get; set; }
        public int InspectionID { get; set; }
        public int ResultID { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }

    }
}

loginExample/Models/InspectionItemDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace loginExample.Models
{
    public class InspectionItemDetails
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ItemID { get; set; }
        public int InspectionID { get; set; }
        public int ResultID { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string resultDescription { get; set; }
    }
}

loginExample/Controllers/InspectionController.cs
using loginExample.Data;
using loginExample.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Providers.Entities;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;
using System.Text;
using HtmlAgilityPack;
using System.IO;


namespace loginExample.Controllers
{
    
    [Authorize]
    public class InspectionController : Controller
    {
        private readonly ILogger<InspectionController> _logger;
        private readonly ApplicationDbContext _db;
        

        public InspectionController(ApplicationDbContext db, ILogger<InspectionController> logger)
        {
            _db = db;
            _logger = logger;
        }

        [AllowAnonymous]
        public  IActionResult Index()
        {
          
            string userId = User.Identity.GetUserId();
            var inspections = new List<InspectionDetails>();
            var properties = new List<PropertyDetails>();

            if (User.IsInRole("admin"))
            {
                ViewBag.properties = _db.Property.Where(p => p.active).ToList();
                inspections = (from i in _db.Inspection
                               join p in _db.Property on i.PropertyID equals p.PropertyID
                               where i.Active
                               select new InspectionDetails
                               {
                                   Active = i.Active,
                                   Details = i.Details,
                                   InspectionDate = i.InspectionDate,
                                   InspectionID = i.InspectionID,
                                   InspectionStatus = i.InspectionStatus,
                                   PropertyID = i.PropertyID,
                                   PropertyName = p.PropertyName

                               }).ToList();
            }

            else if (User.IsInRole("owner"))
            {
                ViewBag.properties = _db.Property.Where(p => p.active && p.UserId == userId).ToList();
                inspections = (from i in _db.Inspection
                               join p in _db.Property on i.PropertyID equals p.PropertyID
                               where i.Active && p.UserId == userId
                               select new InspectionDetails
                               {
                                   Active = i.Active,
                                   Details = i.Details,
                                   InspectionDate = i.InspectionDate,
                                   InspectionID = i.InspectionID,
                                   InspectionStatus = i.InspectionStatus,
                                   PropertyID = i.PropertyID,
                                   PropertyName = p.PropertyName

                               }).ToList();
            }
            else {

                List<int> propertyIds = (from r in _db.Rental                                 
                                  where r.UserID == userId && r.EndDate >= new DateTime()
                                  select  r.PropertyID

                                  ).ToList(); 
                

                if(propertyIds.Count > 0) {
                    inspections = (from i in _db.Inspection
                                   join p in _db.Property on i.PropertyID equals p.PropertyID
                                   where i.Active && propertyIds.Contains(p.PropertyID)
                                   select new InspectionDetails
                                   {
                                       Active = i.Active,
                                       Details = i.Details,
                                       InspectionDate = i.InspectionDate,
                                       InspectionID = i.InspectionID,
                                       InspectionStatus = i.InspectionStatus,
                                       PropertyID = i.PropertyID,
                                       PropertyName = p.PropertyName

                                   }).ToList();
                }

            }
            return View(inspections);

        }

        [HttpPost]
        public FileResult Export(string GridHtml)
        {
            if(GridHtml == null)
            {
                GridHtml = "No Data Available to show";
            }

            HtmlNode.ElementsFlags["img"] = HtmlElementFlag.Closed;
            HtmlNode.ElementsFlags["input"] = HtmlElementFlag.Closed;
            HtmlDocument doc = new HtmlDocument();
            doc.OptionFixNestedTags = true;
            doc.LoadHtml(GridHtml);
            GridHtml = doc.DocumentNode.OuterHtml;

            using (MemoryStream stream = new System.IO.MemoryStream())
            {
                Encoding unicode = Encoding.UTF8;
                StringReader sr = new StringReader(GridHtml);
                Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 100f, 0f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "ScheduledInspections.pdf");
            }
        }


        [Authorize(Roles = "admin, owner")]
        [HttpPost]
        public async Task<IActionResult> Upsert(InspectionDetails inspectionDetails, Inspection inspection)
        {
            if (inspectionDetails.InspectionID == 0)
            {
                var inspectionCount = _db.Inspection.Count(i => i.PropertyID.Equals(inspectionDetails.PropertyID));
                
                if (inspectionCount == 0)
                {
                    inspection.Active = true;
                    await _db.Inspection.AddAsync(inspection);
                    await _db.SaveChangesAsync();
                    //ViewBag.Message = "Added New User Successfully";
                    return RedirectToAction("Index");
                }
                
                else
                {
                    return RedirectToAction("Index");
                    // name already exists
                }
            }

            else
            {
                inspection.Active = true;
                _db.Inspection.Update(inspection);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
                //  ViewBag.Message = "Updated User Details Successfully";
            }

        }

        [Authorize(Roles = "admin, owner")]
        [HttpPost]
        public async Task<IActionResult> Delete(Inspection inspection)
        {
            inspection.Active = false;
            _db.Inspection.Attach(inspection).Property(i => i.Active).IsModified = true;
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        [AllowAnonymous]
        public IActionResult InspectionItems(int InspectionID)
        {
            ViewBag.inspectionResult = _db.InspectionResult.ToList();

            var inspectionItems = (from i in _db.InspectionItem
                                    join r in _db.InspectionResult on i.ResultID equals r.ResultID
                                    where (i.Active && i.InspectionID == InspectionID)
                                    select new InspectionItemDetails
                                    {
                                        ItemID = i.ItemID,
                                        Active = i.Active,
                                        InspectionID = i.InspectionID,
                                        ResultID = i.ResultID,
                                        Name = i.Name,
                                        Notes = i.Notes,
                                        Description = i.Description,
                                        resultDescription = r.Description
                                    }).ToList();

            return View(inspectionItems);

        }


        [Authorize(Roles = "admin, owner")]
        [HttpPost]
        public async Task<IActionResult> UpsertItem(InspectionItemDetails inspectionItemDetails, InspectionItem inspectionItem)
        {
            if (inspectionItemDetails.ItemID == 0)
            {
                
                inspectionItem.Active = true;
                await _db.InspectionItem.AddAsync(inspectionItem);
                await _db.SaveChangesAsync();

                return RedirectToAction("InspectionItems", new { InspectionID = inspectionItem.InspectionID });
            }

            else
            {
                inspectionItem.Active = true;
                _db.InspectionItem.Update(inspectionItem);
                await _db.SaveChangesAsync();
                return RedirectToAction("InspectionItems", new { InspectionID = inspectionItem.InspectionID });
              
            }

        }

        [Authorize(Roles = "admin, owner")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(InspectionItem inspectionItem)
        {
            inspectionItem.Active = false;
            _db.InspectionItem.Attach(inspectionItem).Property(i => i.Active).IsModified = true;
            await _db.SaveChangesAsync();

            return RedirectToAction("InspectionItems", new { InspectionID = inspectionItem.InspectionID });
        }

    }
}

loginExample/Views/Inspection/Index.cshtml
@{
    ViewData["Title"] = "Inspection Page";
}
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model IEnumerable<InspectionDetails>

<h4>Inspection Details</h4>
@if (User.IsInRole("owner"))
{
    @if (Model.Count() > 0)
    {
        @using (Html.BeginForm("Export", "Inspection", FormMethod.Post))
        {
            <input type="hidden" name="GridHtml" />
            <input type="submit" id="btnSubmit" value="Export" title="Export Data to PDF Report" />
        }
    }
    else if (Model.Count() <= 0)
    {
        {
            <input type="hidden" name="GridHtml" />
            <input type="submit" id="btnSubmit" value="Export" disabled title="No Data to export to PDF Report" />
        }
    }
}
else if (User.IsInRole("admin"))
{
    @if (Model.Count() > 0)
    {
        @using (Html.BeginForm("Export", "Inspection", FormMethod.Post))
        {
            <input type="hidden" name="GridHtml" />
            <input type="submit" id="btnSubmit" value="Export" title="Export Data to PDF Report" />
        }
    }
    else if (Model.Count() <= 0)
    {
        {
            <input type="hidden" name="GridHtml" />
            <input type="submit" id="btnSubmit" value="Export" disabled title="No Data to export to PDF Report" />
        }
    }
}

@if (User.IsInRole("admin") || User.IsInRole("owner"))
{
    <div class="addRow">
        <button onclick="editRow(this)" class="btn btn-primary btn-sm">Add Inspection</button>
        <div class="modal">
            <div class="modal-content">
                <div class="modal-title">
                    Add Insection
                    <span class="close" onclick="closeEdit(this)">&times;</span>
                </div>
                <partial name="_UpsertInspection" model="new InspectionDetails()" />
            </div>
        </div>
    </div>
}

@if (Model.Count() > 0)
{

    <table style="width:100%" border="1" class="table">
        <thead class="thead-dark">
            <tr>
                <th>Property Name</th>
                <th>Details</th>
                <th>Inspection Date</th>
                <th>Inspection Status</th>
                <th></th>

            </tr>
        </thead>
        <tbody>
            @foreach (InspectionDetails inspection in Model)
            {
                <partial name="_InspectionDetails" model="@inspection" />
            }
        </tbody>
    </table>
    @if (User.IsInRole("owner"))
    {
        <div id="Grid" hidden>
            @Html.Partial("InspectionReportPartialView", Model)
        </div>
    }
    else if(User.IsInRole("admin"))
    {
    <div id="GridAdmin" hidden>
        @Html.Partial("InspectionReportAdmin", Model)
    </div>
    }
}
else
{
    <p>No Data</p>
}


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
@if (User.IsInRole("owner"))
{
    <script type="text/javascript">
        $(function () {
            $("#btnSubmit").click(function () {
                $("input[name='GridHtml']").val($("#Grid").html());
            });
        });
    </script>
}

@if (User.IsInRole("admin"))
{
    <script type="text/javascript">
        $(function () {
            $("#btnSubmit").click(function () {
                $("input[name='GridHtml']").val($("#GridAdmin").html());
            });
        });
    </script>
}

loginExample/Views/Inspection/InspectionItems.cshtml
@{
    ViewData["Title"] = "Inspection Items Page";
}
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model IEnumerable<InspectionItemDetails>

<h4>Inspection Items</h4>

<form id="deleteUserForm" method="post" action="/Inspection">
    <button type="submit" class="btn-secondary text-white float-left" onclick="closeEdit(this)" data-dismiss="modal" data-toggle="tooltip" data-placement="bottom" title="Return to Inspection Details">
        <i class="fas fa-arrow-left"></i>
    </button>
</form>


@if (User.IsInRole("admin") || User.IsInRole("owner"))
{
    <div class="addRow">
        <button onclick="editRow(this)" class="btn btn-primary btn-sm float-left">Add Item</button>
        <div class="modal">
            <div class="modal-content">
                <div class="modal-title">
                    Add Items
                    <span class="close" onclick="closeEdit(this)">&times;</span>
                </div>
                <partial name="_UpsertInspectionItem" model="new InspectionItemDetails()" />
            </div>
        </div>
    </div>
}

    @if (Model.Count() > 0)
    {

        <table style="width:100%" border="1" class="table">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Notes</th>
                    <th>Result</th>
                    @if (User.IsInRole("admin") || User.IsInRole("owner"))
                    {
                        <th></th>
                    }
                    </tr>
            </thead>
            <tbody>
                @foreach (InspectionItemDetails inspectionItem in Model)
                {
                    <partial name="_InspectionItemDetails" model="@inspectionItem" />
                }
            </tbody>
        </table>

    }
    else
    {
        <p>No Data</p>
    }

loginExample/Views/Inspection/InspectionReportAdmin.cshtml
@model IEnumerable<InspectionDetails>

<html>
<head>
    <h3 align="center">All Scheduled Property Inspections Report for all Properties</h3>
</head>
<body>
    if (inspection.Active == true)
    {
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>Scheduled Inspections:</p>
    <p>&nbsp;</p>
    <table style="width:100%" border="1" align="center">
        <tr style="background-color: #262424;border: 1px solid #ccc; color: white;" align="center">
            <th>Property Name</th>
            <th>Inspection Date</th>
            <th>Details</th>
            <th>Has Taken Place (Yes/No)</th>
        </tr>
        @foreach (InspectionDetails data in Model)
        {
            <tr align="center">
                <td style="width:120px;border: 1px solid #ccc">@data.PropertyName</td>
                <td style="width:120px;border: 1px solid #ccc">@data.InspectionDate</td>
                <td style="width:120px;border: 1px solid #ccc">@data.Details</td>
                @if (data.InspectionStatus == true)
                {
                    <td style="width:120px;border: 1px solid #ccc">Yes</td>

                }
                else
                {
                    <td style="width:120px;border: 1px solid #ccc">No</td>
                }
            </tr>
        }
    </table>
    }


    <div>

    </div>
    <br /><br />
    <p>&nbsp;</p><p>To Whom it may concern,</p><p>&nbsp;</p><p> This is a legitimate report that was supplied by HouseJunkey on @DateTime.Today. Should you have any enquires please don't hesitate to contact us.</p><p>&nbsp;</p><p> Kind Regards,</p><p>HouseJunkey Management.</p>
    <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>Email: Info@Housejunkey.com</p><p>Tel.: 041 321 3391</p><p>Address: 123 Cape Road,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Newton Park,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Port Elizabeth</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6001</p>

</body>
</html> 

loginExample/Views/Inspection/InspectionReportPartialView.cshtml
@model IEnumerable<InspectionDetails>

<html>
    <head>
        <h3 align="center">Schedule Property Inspections Report of all Properties Belonging to @User.Identity.Name</h3>
    </head>
    <body>
            if (inspection.Active == true)
            {
                <p>&nbsp;</p>
                <p>&nbsp;</p>
                <p>Scheduled Inspections:</p>
                <p>&nbsp;</p>
                <table style="width:100%" border="1" align="center">
                    <tr style="background-color: #262424;border: 1px solid #ccc; color: white;" align="center">
                        <th>Property Name</th>
                        <th>Inspection Date</th>
                        <th>Details</th>
                        <th>Has Taken Place (Yes/No)</th>
                    </tr>
                @foreach (InspectionDetails data in Model)
                 {
                    <tr align="center">
                        <td style="width:120px;border: 1px solid #ccc">@data.PropertyName</td>
                        <td style="width:120px;border: 1px solid #ccc">@data.InspectionDate</td>
                        <td style="width:120px;border: 1px solid #ccc">@data.Details</td>
                    @if (data.InspectionStatus == true)
                    {
                        <td style="width:120px;border: 1px solid #ccc">Yes</td>

                    }
                    else
                    {
                        <td style="width:120px;border: 1px solid #ccc">No</td>
                    }
                </tr>
                    }
                </table>
            }
        

        <div>

        </div>
        <br /><br />
        <p>&nbsp;</p><p>To Whom it may concern,</p><p>&nbsp;</p><p> This is a legitimate report that was supplied by HouseJunkey on @DateTime.Today. Should you have any enquires please don't hesitate to contact us.</p><p>&nbsp;</p><p> Kind Regards,</p><p>HouseJunkey Management.</p>
        <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>Email: Info@Housejunkey.com</p><p>Tel.: 041 321 3391</p><p>Address: 123 Cape Road,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Newton Park,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Port Elizabeth</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6001</p>

    </body>
</html> 

loginExample/Views/Inspection/_InspectionDetails.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model InspectionDetails
    
    <tr>
        <td>@Model.PropertyName</td>
        <td>@Model.Details</td>
        <td>@Model.InspectionDate</td>
        <td>@Model.InspectionStatus</td>
        <td>

            <form id="deleteUserForm" method="post" action="/Inspection/InspectionItems">
                <input class="col-6" type="hidden" id="txtInspectionID" name="InspectionID" asp-for="InspectionID" />
                <button type="submit" class="btn btn-link" data-toggle="tooltip" data-placement="bottom" title="View Inspected Items">
                    <i class="fas fa-search-plus"></i>
                </button>
            </form>

            @if (User.IsInRole("admin") || User.IsInRole("owner"))
            {

                <div class="editRow">
                    <button onclick="editRow(this)" class="btn btn-link" data-toggle="tooltip" data-placement="bottom" title="Edit this Inspection">
                        <i class="fas fa-edit"></i>
                    </button>
                    <div class="modal">
                        <div class="modal-content">
                            <div class="modal-title">
                                Edit Insection
                                <span class="close" onclick="closeEdit(this)">&times;</span>
                            </div>
                            <partial name="_UpsertInspection" model="Model" />
                        </div>
                    </div>
                </div>

                <div class="deleteRow">
                    <button onclick="deleteRow(this)" class="btn btn-link" data-toggle="tooltip" data-placement="bottom" title="Delete this Inspection">
                        <i class="far fa-trash-alt"></i>
                    </button>
                    <div class="modal">
                        <div class="modal-content">
                            <div class="modal-title">
                                Delete Insection
                                <span class="close" onclick="closeEdit(this)">&times;</span>
                            </div>
                            <form id="deleteUserForm" method="post" action="/Inspection/Delete">

                                <input class="col-6" type="hidden" id="txtInspectionID" name="InspectionID" asp-for="InspectionID" />
                                <p>Are you sure you want to delete @Model.Details?</p>

                                <div class="float-right">
                                    <button type="button" class="btn btn-secondary text-white" onclick="closeEdit(this)" data-dismiss="modal">Cancel</button>
                                    <button type="submit" class="btn btn-success text-white">Delete</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            }
            </td>
    </tr>

loginExample/Views/Inspection/_InspectionItemDetails.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model InspectionItemDetails
    
<tr>
    <td>@Model.Name</td>
    <td>@Model.Description</td>
    <td>@Model.Notes</td>
    <td>@Model.resultDescription</td>

    @if (User.IsInRole("admin") || User.IsInRole("owner"))
    {
        <td>

            <div class="editRow">
                <button onclick="editRow(this)" class="btn btn-link" data-toggle="tooltip" data-placement="bottom" title="Edit the Inspected Item">
                    <i class="fas fa-edit"></i>
                </button>
                <div class="modal">
                    <div class="modal-content">
                        <div class="modal-title">
                            Edit Item
                            <span class="close" onclick="closeEdit(this)">&times;</span>
                        </div>
                        <partial name="_UpsertInspectionItem" model="Model" />
                    </div>
                </div>
            </div>

            <div class="deleteRow">
                <button onclick="deleteRow(this)" class="btn btn-link" data-toggle="tooltip" data-placement="bottom" title="Delete the Inspected Item">
                    <i class="far fa-trash-alt"></i>
                </button>
                <div class="modal">
                    <div class="modal-content">
                        <div class="modal-title">
                            Delete Item
                            <span class="close" onclick="closeEdit(this)">&times;</span>
                        </div>
                        <form id="deleteUserForm" method="post" action="/Inspection/DeleteItem">

                            <input class="col-6" type="hidden" id="txtItemID" name="ItemID" asp-for="ItemID" />
                            <input class="col-6" type="hidden" id="txtInspectionID" name="InspectionID" asp-for="InspectionID" />
                            <p>Are you sure you want to delete @Model.Name?</p>

                            <div class="float-right">
                                <button type="button" class="btn btn-secondary text-white" onclick="closeEdit(this)" data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-success text-white">Delete</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>

        </td>
    }
    </tr>

loginExample/Views/Inspection/_UpsertInspection.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@model InspectionDetails


<form id="upsertInspectionForm" method="post" action="/Inspection/Upsert" class="form-group">

    <input class="col-6" type="hidden" id="txtInspectionID" name="InspectionID" asp-for="InspectionID" />

    <div class="form-row form-group">
        <label class="col-4" for="ddlProperties">Property Name</label>

        <select class="col-6 form-control" id="ddlProperties" asp-for="PropertyID" required>
            @foreach (Property property in ViewBag.properties)
            {
                <option value="@property.PropertyID">@property.PropertyName</option>
            }
        </select>
    </div>

    <div class="form-row form-group">
        <label class="col-4" for="txtDetails">Details</label>
        <input class="col-6 form-control" type="text" id="txtDetails" name="Details" asp-for="Details" required/>
    </div>

    <div class="form-row form-group">
        <label class="col-4" for="txtInspectionDate">Inspection Date</label>
        <input class="col-6 form-control" type="date" id="txtInspectionDate" name="InspectionDate" asp-for="InspectionDate" required />
    </div>

    <div class="form-row form-group">
        <label class="col-4" for="txtInspectionStatus">Inspection Status</label>
        <div class="col">
            <input type="checkbox" id="txtInspectionStatus" name="InspectionStatus" asp-for="InspectionStatus"/>
            <label for="txtInspectionStatus">Resolved</label>
        </div>
    </div>


    <div class="form-row float-right"> 
        <button type="button" class="btn btn-secondary text-white" onclick="closeEdit(this)" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success text-white" style="margin-left:5px;">Save</button>
    </div>
</form>
        