RMS22 Final Project/Models/Property.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RMS22_Final_Project.Models
{
    public class Property
    {
        [Key]
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public int UserID { get; set; }
        public int SuburbID { get; set; }       
        public string PropertyDescription { get; set; }
        public int RoomNum { get; set; }
        public string PropertyAddress{ get; set; }          
        
        public bool active { get; set; }

        public int size { get; set; }
        public int ParkNum { get; set; }
        public int BathNum { get; set; }

        public bool AllowPets { get; set; }
        
    }
}

RMS22 Final Project/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RMS22_Final_Project.Models;
using System.Web;
using System.IO;

namespace RMS22_Final_Project.Controllers
{
    public class PropertyController : Controller
    {

        [BindProperty]
        public new Property Property { get; set; }

        private readonly ApplicationDBContext _db;

     
        public PropertyController(ApplicationDBContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            Property = new Property();
            Property.PropertyID = 0;

            //todo get users username, id only
            ViewBag.owners = _db.Users.ToList();
            ViewBag.suburbs = _db.Suburb.ToList();

            return View(Property);
        }

        #region Api Calls   

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var properties = await (from p in _db.Property
                               join s in _db.Suburb on p.SuburbID equals s.SuburbID
                               join u in _db.Users on p.UserID equals u.UserID
                               where p.active == true
                               orderby p.PropertyName
                               select new
                               {
                                   u.UserName,
                                   p.PropertyName,
                                   p.PropertyID,
                                   p.PropertyAddress,
                                   p.PropertyDescription,
                                   p.RoomNum,
                                   p.SuburbID,
                                   p.UserID,
                                   p.active,
                                   p.AllowPets,
                                   p.BathNum,
                                   p.size,
                                   p.ParkNum,
                                   s.SuburbName

                               }).ToListAsync();

            return Json(new { data = properties });
        }


        [HttpPost]
        public async Task<IActionResult> Delete(Property property)
        {
            property.active = false;
            _db.Property.Attach(property).Property(p => p.active).IsModified = true;
            await _db.SaveChangesAsync();
           
            return RedirectToAction("Index");

        }


        [HttpPost]
        public async Task<IActionResult> Upsert(Property property)
        {
            if (property.PropertyID == 0)
            {

                var propertyCount = await _db.Property.CountAsync(p => p.PropertyName.Equals(property.PropertyName));

                if (propertyCount == 0)
                {
                    property.active = true;
                    await _db.Property.AddAsync(property);
                    await _db.SaveChangesAsync();
                    // ViewBag.Message = "Added New User Successfully";
                    return RedirectToAction("Index");
                }
                else {
                    return RedirectToAction("Index");
                    // name already exists
                }
            }
            else
            {
                property.active = true;
                _db.Property.Update(property);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
                //  ViewBag.Message = "Updated User Details Successfully";
            }
        }

        [HttpPost]
        public IActionResult UploadImage(HttpPostAttribute file)
        {
            
               //fix using HttpPostedFilebased ?  
           // int d = 5;

            return RedirectToAction("Index");

        }


        #endregion

    }
}

RMS22 Final Project/Views/Property/Index.cshtml
@model RMS22_Final_Project.Models.Property
@Html.ValidationSummary(false, "", new { @class = "text-danger" })


<div class="container">
    <div class="modal fade" id="upsertProperty" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Property Details</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form id="upsertPropertyForm" method="post" action="/Property/Upsert">
                        <input class="col-6" type="hidden" id="txtPropertyID" name="PropertyID" asp-for="PropertyID" />


                        <label class="col-4" for="txtPropertyName">Name</label>
                        <input class="col-6" type="text" id="txtPropertyName" name="PropertyName" asp-for="PropertyName" />

                        <label class="col-4" for="txtRoomNum">Bedrooms</label>
                        <input class="col-6" type="number" id="txtRoomNum" name="RoomNum" asp-for="RoomNum" />

                        <label class="col-4" for="txtBathNum">Bathrooms</label>
                        <input class="col-6" type="number" id="txtBathNum" name="BathNum" asp-for="BathNum" />

                        <label class="col-4" for="txtParkNum">Parkings</label>
                        <input class="col-6" type="number" id="txtParkNum" name="ParkNum" asp-for="ParkNum" />

                        <label class="col-4" for="txtSize">Floor Size</label>
                        <input class="col-6" type="number" id="txtSize" name="size" asp-for="size" />

                        <label class="col-4" for="txtPropertyAddress">Address</label>
                        <input class="col-6" type="text" id="txtPropertyAddress" name="PropertyAddress" asp-for="PropertyAddress" />

                        <label class="col-4" for="cbAllowPets">Allow Pets</label>
                        <input class="col-6" type="checkbox" id="cbAllowPets" name="PropertyAddress" asp-for="PropertyAddress" />

                        <label class="col-4" for="ddlSuburbID">Suburb</label>
                        <select class="col-6" id="ddlSuburbID" asp-for="SuburbID" required>
                            @foreach (Suburb suburb in ViewBag.suburbs)
                            {
                                <option value="@suburb.SuburbID">@suburb.SuburbName</option>
                            }
                        </select>

                        <label class="col-4" for="ddlUserID">Owner</label>
                        <select class="col-6" id="ddlUserID" asp-for="UserID" required>
                            @foreach (User owners in ViewBag.owners)
                            {
                                <option value="@owners.UserID">@owners.UserName</option>
                            }
                        </select>

                        <label class="col-4" for="txtPropertyDescription">Description</label>
                        <textarea class="col-8 text-upsert-areas" id="txtPropertyDescription" name="PropertyDescription" name="PropertyDescription" asp-for="PropertyDescription"></textarea>

                        <div class="float-right upsert-buttons">
                            <button type="button" class="btn btn-secondary text-white" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-success text-white">Save</button>
                        </div>

                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="container">
    <div class="modal fade" id="deleteProperty" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Delete Property</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form method="post" action="/Property/Delete">
                        <p>Are you sure you want to delete this property?</p>
                        <input class="col-6" type="hidden" id="txtDeletePropertyID" name="PropertyID" asp-for="PropertyID" />

                        <div class="float-right">
                            <button type="button" class="btn btn-secondary text-white" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-danger text-white">Delete</button>
                        </div>

                    </form>
                </div>
            </div>

        </div>
    </div>
</div>


<div class="container">
    <div class="modal fade" id="propertyImages" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Property Images</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">

                    @using (Html.BeginForm("UploadImage", "Property", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="row">
                            <label for="img" class="col-2">Upload image:</label>
                            <input type="file" id="file" name="img" value="Browse" class="col-8" style="overflow: hidden;" />
                            <div class="col-2">
                                <input type="submit" value="Upload" class="btn btn-success text-white float-right" />
                            </div>
                        </div>

                    }

                    <hr />

                    @*<div class="row">
            <label for="ddlDeleteImage" class="col-2">Delete images</label>
            <select class="col-5" id="ddlDeleteImage">
                <option value="1">img1</option>
                <option value="2">img2</option>
                <option value="3">img3</option>
            </select>
            <div class="col-5">
                <button type="button" class="btn btn-danger text-white float-right btn-sm" data-dismiss="modal">Delete</button>
            </div>
        </div>*@

                    @* List all the images in the correct folder *@

                    <br />
                    <div class="row">
                        <div class="col-6">
                            <input type="checkbox" />
                            <label>img1.jpg</label>
                            <br />
                            <img src="~/images/property/2/1.JPG" width="300" />
                        </div>
                        <div class="col-6">
                            <input type="checkbox" />
                            <label>img2.jpg</label>
                            <br />
                            <img src="~/images/property/2/5.JPG" width="300" />
                        </div>
                        <div class="col-6">
                            <input type="checkbox" />
                            <label>img3.jpg</label>
                            <br />
                            <img src="~/images/property/2/3.JPG" width="300" />
                        </div>
                        <div class="col-6">
                            <input type="checkbox" />
                            <label>img4.jpg</label>
                            <br />
                            <img src="~/images/property/2/4.JPG" width="300" />
                        </div>
                    </div>
                
                    <div class="float-right">
                        <button type="button" class="btn btn-danger text-white"  data-dismiss="modal">Delete</button>
                        <button type="button" class="btn btn-secondary text-white" data-dismiss="modal">Cancel</button>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


<div class="container row p-0 a-0">
    <div class="col-12">
        <h1 class="float-left">Property Manager</h1>
        <button type="button" class="btn btn-info table-header-buttons" onclick="Upsert()">Add Property</button>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-bordered table-striped display compact" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Bedrooms</th>
                    <th>Bathrooms</th>
                    <th>Parking</th>
                    <th>Floor Size</th>
                    <th>Pet Friendly</th>
                    <th>Address</th>
                    <th>Suburb</th>
                    <th>Owner</th>
                    <th>Description</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>

</div>

@section Scripts {
    <script src="~/js/Property.js"></script>
}